import { afterEach, expect, test, describe, beforeAll, afterAll } from "vitest";
import { render, screen } from "@testing-library/react";
import Carousel from "../src/components/Carousel/CarouselComponent";
import { setupServer } from "msw/node";
import { http, HttpResponse } from "msw";

const repos = [
  {
    id: 271365549,
    name: "agenda-live",
    html_url: "https://github.com/matheusgomessouza/agenda-live",
    description:
      "Código desenvolvido com base na playlist Angular Course 9 sobre a mentoria de Michelli Brito (@MichelliBrito) / Code developed based on the Angular Course 9 playlist mentored by Michelli Brito (@MichelliBrito)",
    created_at: "2020-06-10T19:21:46Z",
    updated_at: "2024-05-06T12:15:03Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["angular", "css", "html", "typescript"],
    language: "TypeScript",
  },
  {
    id: 249829125,
    name: "be-the-hero",
    html_url: "https://github.com/matheusgomessouza/be-the-hero",
    description:
      "Código produzido durante a Semana OmniStack 11.0 / Code produced during OmniStack Week 11.0",
    created_at: "2020-03-24T22:11:16Z",
    updated_at: "2022-03-01T21:13:16Z",
    homepage: "",
    license: null,
    topics: ["axios", "nodejs", "react-native", "reactjs"],
    language: "JavaScript",
  },
  {
    id: 250783754,
    name: "casa-criativa",
    html_url: "https://github.com/matheusgomessouza/casa-criativa",
    description:
      'Projeto "Casa Criativa" desenvolvido durante a Semana Omnistack 11.0 com a mentoria de Mayk Brito / Project "Creative House" developed during Omnistack week 11.0 under the mentorship of Mayk Brito',
    created_at: "2020-03-28T12:00:26Z",
    updated_at: "2022-03-03T19:15:59Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: [
      "css",
      "expressjs",
      "html",
      "javascript",
      "nodejs",
      "nunjucks",
      "sqlite",
    ],
    language: "CSS",
  },
  {
    id: 384591144,
    name: "code",
    html_url: "https://github.com/matheusgomessouza/code",
    description: null,
    created_at: "2021-07-10T02:12:27Z",
    updated_at: "2021-07-14T03:28:27Z",
    homepage: null,
    license: null,
    topics: [],
    language: "Go",
  },
  {
    id: 755288348,
    name: "community-cares",
    html_url: "https://github.com/matheusgomessouza/community-cares",
    description: "Mobile app created using Expo + React Native",
    created_at: "2024-02-09T20:18:36Z",
    updated_at: "2024-05-10T14:03:43Z",
    homepage: "",
    license: null,
    topics: ["axios", "expo", "jest", "react-native", "typescript"],
    language: "TypeScript",
  },
  {
    id: 764641039,
    name: "community-cares-server",
    html_url: "https://github.com/matheusgomessouza/community-cares-server",
    description: "Community Cares server",
    created_at: "2024-02-28T12:58:40Z",
    updated_at: "2024-03-04T19:59:01Z",
    homepage: "https://community-cares-server.vercel.app",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["axios", "expressjs", "husky", "nodejs", "typescript", "vitest"],
    language: "TypeScript",
  },
  {
    id: 443418158,
    name: "context-api-challenge",
    html_url: "https://github.com/matheusgomessouza/context-api-challenge",
    description:
      "Proposta de desafio para refatorar um aplicativo e compartilhar o estado entre os componentes / Challenge proposal for re-factoring an application and share state between components",
    created_at: "2021-12-31T20:06:28Z",
    updated_at: "2022-03-01T14:19:00Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["reactjs"],
    language: "TypeScript",
  },
  {
    id: 577906454,
    name: "crud-springboot-jpa",
    html_url: "https://github.com/matheusgomessouza/crud-springboot-jpa",
    description: "CRUD criado utilizando Springboot Java e JPA",
    created_at: "2022-12-13T19:55:18Z",
    updated_at: "2022-12-13T20:02:24Z",
    homepage: null,
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: [],
    language: "Java",
  },
  {
    id: 629719560,
    name: "dispear",
    html_url: "https://github.com/matheusgomessouza/dispear",
    description: "Song created with Sonic Pi coding music environment",
    created_at: "2023-04-18T22:24:21Z",
    updated_at: "2024-05-18T20:55:16Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["ruby", "sonic-pi"],
    language: "Ruby",
  },
  {
    id: 448674305,
    name: "dtmoney",
    html_url: "https://github.com/matheusgomessouza/dtmoney",
    description:
      "Project developed during chapter II of Ignite course of Rocketseat / Projeto desenvolvido durante o capítulo II do curso Ignite da Rocketseat",
    created_at: "2022-01-16T21:12:17Z",
    updated_at: "2022-03-01T21:50:46Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["miragejs", "reactjs", "styled-components", "typescript"],
    language: "TypeScript",
  },
  {
    id: 375586493,
    name: "e-diaristas",
    html_url: "https://github.com/matheusgomessouza/e-diaristas",
    description:
      "Esse projeto foi desenvolvido durante a semana TreinaWeb Multi-stack. / This project was developed during the TreinaWeb Multi-stack week.",
    created_at: "2021-06-10T05:57:32Z",
    updated_at: "2022-03-02T16:45:00Z",
    homepage: "",
    license: null,
    topics: [
      "expo",
      "laravel",
      "material-ui",
      "nextjs",
      "react-native",
      "typescript",
    ],
    language: "JavaScript",
  },
  {
    id: 505628920,
    name: "event-platform",
    html_url: "https://github.com/matheusgomessouza/event-platform",
    description:
      "Projeto construído durante o Ignite Lab / Project built during Ignite Lab",
    created_at: "2022-06-20T23:37:42Z",
    updated_at: "2022-06-25T01:53:19Z",
    homepage: "event-platform-ashy.vercel.app",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["apollo", "graphcms", "graphql", "jest", "nextjs", "reactjs"],
    language: "TypeScript",
  },
  {
    id: 622944305,
    name: "express-prisma-api",
    html_url: "https://github.com/matheusgomessouza/express-prisma-api",
    description: "API created using ExpressJS framework + Prisma ORM",
    created_at: "2023-04-03T11:37:18Z",
    updated_at: "2023-04-03T12:03:54Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["express-js", "prisma-orm", "typescript", "vitest"],
    language: "TypeScript",
  },
  {
    id: 802632941,
    name: "fast-paced",
    html_url: "https://github.com/matheusgomessouza/fast-paced",
    description: "Song created with Sonic Pi coding music environment",
    created_at: "2024-05-18T20:43:56Z",
    updated_at: "2024-05-18T20:54:44Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["ruby", "sonic-pi"],
    language: "Ruby",
  },
  {
    id: 488051241,
    name: "feedback-widget",
    html_url: "https://github.com/matheusgomessouza/feedback-widget",
    description:
      "Projeto construído durante o Next Level Week #08 / Project built during Next Level Week #08",
    created_at: "2022-05-03T02:10:31Z",
    updated_at: "2022-05-28T03:03:20Z",
    homepage: "feedback-widget-xi.vercel.app",
    license: null,
    topics: [
      "axios",
      "expo",
      "expressjs",
      "headlessui",
      "jest",
      "nodejs",
      "prisma",
      "reactjs",
      "sqlite3",
      "tailwindcss",
      "typescript",
    ],
    language: "TypeScript",
  },
  {
    id: 441268820,
    name: "github-explorer",
    html_url: "https://github.com/matheusgomessouza/github-explorer",
    description: null,
    created_at: "2021-12-23T18:47:55Z",
    updated_at: "2021-12-28T01:31:16Z",
    homepage: null,
    license: null,
    topics: [],
    language: "JavaScript",
  },
  {
    id: 370514774,
    name: "inmana",
    html_url: "https://github.com/matheusgomessouza/inmana",
    description:
      "Prevenção de perdas com gerenciamento inteligente da data de validade.  /  Loss prevention with smart expiration date management.",
    created_at: "2021-05-24T23:57:57Z",
    updated_at: "2022-03-02T14:03:19Z",
    homepage: "",
    license: null,
    topics: ["elixir", "phoenix", "phoenix-framework"],
    language: "Elixir",
  },
  {
    id: 379126391,
    name: "letmeask",
    html_url: "https://github.com/matheusgomessouza/letmeask",
    description:
      "Projeto desenvolvido durante a Next Level Week Together / Project developed during the Next Level Week Together",
    created_at: "2021-06-22T03:07:45Z",
    updated_at: "2022-03-02T16:32:45Z",
    homepage: "",
    license: null,
    topics: ["firebase", "reactjs", "sass", "typescript"],
    language: "TypeScript",
  },
  {
    id: 355007243,
    name: "matheusgomessouza",
    html_url: "https://github.com/matheusgomessouza/matheusgomessouza",
    description: null,
    created_at: "2021-04-06T00:13:52Z",
    updated_at: "2021-10-26T23:43:45Z",
    homepage: null,
    license: null,
    topics: [],
    language: null,
  },
  {
    id: 664730840,
    name: "mathpholio",
    html_url: "https://github.com/matheusgomessouza/mathpholio",
    description: "This is my personal website.",
    created_at: "2023-07-10T16:06:29Z",
    updated_at: "2024-04-23T13:51:05Z",
    homepage: "https://mathpholio.vercel.app",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["jest", "nextjs", "react", "tailwindcss", "typescript"],
    language: "TypeScript",
  },
  {
    id: 353574479,
    name: "moveit",
    html_url: "https://github.com/matheusgomessouza/moveit",
    description:
      "Projeto desenvolvido durante a Next Level Week #04 / Project developed during the Next Level Week #04",
    created_at: "2021-04-01T04:37:31Z",
    updated_at: "2022-03-02T13:42:51Z",
    homepage: "https://moveit-nextjs-nlw.vercel.app",
    license: null,
    topics: ["nextjs", "typescript"],
    language: "TypeScript",
  },
  {
    id: 373688997,
    name: "my-score-app",
    html_url: "https://github.com/matheusgomessouza/my-score-app",
    description:
      "Desafio proposto para admissão de emprego em empresa multinacional do ramo financeiro e dados / Challenge proposed for admission of employment in a multinational company in the financial and data sector",
    created_at: "2021-06-04T01:39:55Z",
    updated_at: "2022-03-01T20:30:36Z",
    homepage: "https://my-score-app.vercel.app",
    license: null,
    topics: ["eslint", "react", "reactjs", "redux", "sass", "typescript"],
    language: "TypeScript",
  },
  {
    id: 269490718,
    name: "nlw-ecoleta",
    html_url: "https://github.com/matheusgomessouza/nlw-ecoleta",
    description:
      "Projeto construído durante o Next Level Week #01 /  Project built during Next Level Week #01",
    created_at: "2020-06-05T00:04:18Z",
    updated_at: "2023-09-02T23:54:32Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: [
      "express",
      "javascript",
      "nodejs",
      "react",
      "react-native",
      "reactjs",
      "sqlite3",
      "typescript",
    ],
    language: "TypeScript",
  },
  {
    id: 420805586,
    name: "nlw-heat",
    html_url: "https://github.com/matheusgomessouza/nlw-heat",
    description:
      "Projeto desenvolvido durante a Next Level Week Heat / Project develop during the Next Level Week Heat",
    created_at: "2021-10-24T21:59:11Z",
    updated_at: "2022-06-08T00:49:15Z",
    homepage: "",
    license: null,
    topics: [
      "elixir",
      "react-native",
      "reactjs",
      "sass",
      "socket-io",
      "typescript",
    ],
    language: "Elixir",
  },
  {
    id: 580174797,
    name: "notifications-service",
    html_url: "https://github.com/matheusgomessouza/notifications-service",
    description: "Nest.js microservice project for notifications",
    created_at: "2022-12-19T22:40:59Z",
    updated_at: "2022-12-22T16:41:40Z",
    homepage: "",
    license: {
      key: "mit",
      name: "MIT License",
      spdx_id: "MIT",
      url: "https://api.github.com/licenses/mit",
      node_id: "MDc6TGljZW5zZTEz",
    },
    topics: ["nestjs", "nodejs", "prisma"],
    language: "TypeScript",
  },
  {
    id: 359636832,
    name: "plantmanager",
    html_url: "https://github.com/matheusgomessouza/plantmanager",
    description:
      "Aplicação mobile com React Native produzida durante o Next Level Week #05 / Mobile application with React Native produced during Next Level Week #05",
    created_at: "2021-04-20T00:33:06Z",
    updated_at: "2022-03-01T20:28:24Z",
    homepage: "",
    license: null,
    topics: ["expo", "react-native", "typescript"],
    language: "TypeScript",
  },
  {
    id: 367975070,
    name: "podcastr",
    html_url: "https://github.com/matheusgomessouza/podcastr",
    description:
      "Projeto desenvolvido durante a Next Level Week #05 / Project developed during the Next Level Week #05",
    created_at: "2021-05-16T20:06:41Z",
    updated_at: "2022-03-02T13:54:15Z",
    homepage: "",
    license: null,
    topics: ["axios", "nextjs", "reactjs", "sass", "typescript"],
    language: "TypeScript",
  },
  {
    id: 405699046,
    name: "proffy",
    html_url: "https://github.com/matheusgomessouza/proffy",
    description:
      "Projeto desenvolvido durante a Next Level Week #2 / Project developed during the Next Level Week #2",
    created_at: "2021-09-12T16:49:44Z",
    updated_at: "2022-03-02T13:34:04Z",
    homepage: "",
    license: null,
    topics: ["expo", "javascript", "react-native", "reactjs", "typescript"],
    language: "TypeScript",
  },
  {
    id: 343558453,
    name: "rocketpay",
    html_url: "https://github.com/matheusgomessouza/rocketpay",
    description: "API de pagamentos em Elixir / Payments API in Elixir",
    created_at: "2021-03-01T21:11:19Z",
    updated_at: "2022-03-02T16:42:44Z",
    homepage: "",
    license: null,
    topics: ["ecto", "elixir", "phoenix", "phoenix-framework"],
    language: "Elixir",
  },
  {
    id: 371367270,
    name: "search-hero",
    html_url: "https://github.com/matheusgomessouza/search-hero",
    description:
      "Mecanismo de busca de personagens da Marvel, utilizando a API da Marvel Comics™️ / Search mechanism of Marvel characters that uses Marvel's free API ",
    created_at: "2021-05-27T12:34:49Z",
    updated_at: "2022-03-03T19:22:46Z",
    homepage: "",
    license: null,
    topics: [
      "axios",
      "crypto-js",
      "reactjs",
      "styled-components",
      "typescript",
    ],
    language: "TypeScript",
  },
];

export const restHandlers = [
  http.get("/api/github/repos", () => {
    return HttpResponse.json(repos);
  }),
];

const server = setupServer(...restHandlers);

describe("Carousel component", () => {
  // Start server before all tests
  beforeAll(() => server.listen({ onUnhandledRequest: "error" }));
  // Configuring the server with onUnhandleRequest: 'error' ensures that an error is thrown whenever there is a request that does not have a corresponding request handler.

  //  Close server after all tests
  afterAll(() => server.close());

  // Reset handlers after each test `important for test isolation`
  afterEach(() => server.resetHandlers());

  test("if component has an carousel child component", async () => {
    render(<Carousel />);
    // mock the API response
    expect(screen.findByRole("slider")).toBeDefined();
  });
});
